---- Function to load a script... dont bother
--function loadScript(scriptName)
--  print("Loading script: " .. scriptName)
--  dofile(scriptName)
--end
--
---- load fivem natives
--loadScript("fivem_natives.lua")
--
---- load script to test
--loadScript("[extra]/StrictPolice/client.lua")
